name: One-Click Build & Publish APK (subfolder)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Bootstrap Gradle wrapper (if missing)
        working-directory: YIDOSTEEL-v11.2-android
        run: |
          if [ ! -f ./gradlew ]; then
            wget -q https://services.gradle.org/distributions/gradle-8.7-bin.zip -O gradle.zip
            unzip -q gradle.zip -d gradle8 && rm gradle.zip
            gradle8/gradle-8.7/bin/gradle wrapper
          fi
          chmod +x ./gradlew

      - name: Assemble Debug APK
        working-directory: YIDOSTEEL-v11.2-android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: YIDOSTEEL-v11.2-android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub Release (optional)
        uses: ncipollo/release-action@v1
        with:
          tag: "apk-${{ github.run_number }}"
          name: "APK ${{ github.run_number }}"
          draft: false
          prerelease: false
          artifacts: "YIDOSTEEL-v11.2-android/app/build/outputs/apk/debug/app-debug.apk"
